# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/

      # Example: Deploy step (customize as needed)
      # - name: Deploy to server
      #   run: |
      #     echo "Deploying package..."
      #     # Add your deployment commands here
