name: PYTHON CI

on:
  push:
    branches: [dev, test, main]
  pull_request:
    branches: [dev, test, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # - name: Run tests
      #   run: |
      #     pip install pytest
      #      pytest tests/
      - name: Build package
        run: |
          python -m pip install build
          python -m build

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/
